### ISSUE TITLE
Unable to resize font size for body posts <p>

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [nraboy/hugo-phlat-theme#13]
Hi, i have edited the bootstrap.css file to replace 14px size to 16px but it's not working.

my repo is https://github.com/hashhackers/marketplace

site is https://market.hashhackers.com

can you help?

**Comment by nraboy** [comment]
Hey @ParveenBhadooOfficial ,

You shouldn't be changing anything in the Bootstrap files. Custom theme CSS should go in **phlat.css** because that CSS file is loaded last and will override everything prior.

Issue tickets are for bugs, so I'm going to close this ticket. If you'd like support for using the theme, I am available for hire:

https://www.thepolyglotdeveloper.com/hire-me/

Otherwise, I encourage you to dig around the theme to see how everything works.

Best,
